name: testing
on:
    pull_request:
        branches: [master]
jobs:
    test:
        strategy:
            matrix:
                os: [ubuntu-latest]
                python: [3.8.10]
        runs-on: ${{ matrix.os }}
        timeout-minutes: 10
        steps:
            - name: Checkout source repository
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
                clean: false

            - name: checkout to current branch
              run: git checkout ${{ env.BRANCH }}

            - name: Install non-python dependencies on Ubuntu
              if: runner.os == 'Linux'
              run: |
                sudo apt-get update -y
                sudo apt-get install libbluetooth-dev -y
            - name: Set up Python ${{ matrix.python }}
              uses: actions/setup-python@v2
              with:
                python-version: ${{ matrix.python }}

            - name: Install Python dependencies
              run: |
                python -m pip install --upgrade pip
                # install explorepy with its test dependencies
                pip install -e .[test]
            - name: Run pytest
              run: |
                  python -m pytest --import-mode=append
